version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      # - npm run export
      - echo "Initializing deployment"
      - cd out
      - echo "Started sync in s3://demo-website-bucket123 bucket"
      - aws s3 sync . "s3://demo-website-bucket123"--delete --exact-timestamps --follow-symlinks --only-show-errors --exclude "s3://demo-website-bucket123/media-cdn/*"
      - aws cloudfront create-invalidation --distribution-id E2LL4MJEVXGH8I --paths "/*"
      - echo "Everything done !!!"
artifacts:
  files:
    - "**/*"
  base-directory: out
